# 깃 허브 연동 중 동기화 오류
프로젝트 파일을 깃허브에 push 하던 중  
```
error: failed to push some refs to '~'  
hint: Updates were rejected because the remote contains work that you do  
To ~  
!	refs/heads/master:refs/heads/master	[rejected] (fetch first)  
hint: not have locally. This is usually caused by another repository pushing  
Done  
hint: to the same ref. You may want to first integrate the remote changes  
hint: (e.g., 'git pull ...') before pushing again.  
hint: See the 'Note about fast-forwards' in 'git push --help' for details.  
```
와 같은 오류가 발생하였다.  
해당 hint 구문을 구글에 검색해보니 깃허브에 저장소를 만들면서 READ.ME 파일을 같이 생성하면서   
push를 하던 중 동일 저장소가 충돌하여 발생한 문제라는 것을 알 수 있었다.   
즉, 깃의 원격저장소와 현재 로컬 저장소가 동기화 되어있지 않기 때문이었다.  

이에 대한 해결 방법은 간단했는데, 이를 동기화 시켜주니 바로 해결되었다.  
```
git pull --rebase 원격저장소별칭 master
```
를 적용시킨 후 오류없이 push를 할 수 있었다.
